### PR TITLE
ComparatorTag

### PR DESCRIPTION
**Pull request by rustle**
*Issue number of the reported bug or feature request: #<number>*

**Describe your changes**
Boxed up string tags in a struct to give them constants and a namespace

**Testing performed**
Existing tests updated

**Additional context**

### CODE REVIEW

**Comment by marciniwanicki** [comment]
Thanks @rustle for the PR and your interest in xcdiff 🙌. Could you please list some examples what kind of requirements `ComparatorTag` can help to solve? Would you like to write some external extensions? What would they do?

**Comment by rustle** [comment]
@marciniwanicki the goal is to give an extensible enum like constant so we get the normal benefits of using constants (avoiding typo bugs, easier refactoring, etc). RawRepresentable enums don't support custom cases or arguments so that seemingly more intuitive route is closed to us.

**Comment by marciniwanicki** [comment]
Thanks @rustle, the code looks good, but I am still a bit unsure if we need it, and if so, it's probably because we have some general design issue. Few thoughts:
- `tag` was supposed to be used only as a plain text prefix to distinguish output coming from different comparators.
- `tag` is not supposed to be any kind of identifier, we want the `ComparatorType` to identify a comparator.
- Having a full list of comparators in `ComparatorType` and `ComparatorTag` might be a little bit confusing.
- `ComparatorTag` does not change a lot from the internal implementation perspective i.e.  `ComparatorTag.dependencies` is used only once in the library code (second usage is in the tests where the string repetition IMHO is acceptable) so the benefit of having the string being statically predefined is not very clear.
- To select individual comparator or a subset, an array of `ComparatorType` needs to be specified, the use case of filtering by tag (as we do it in `CommandRunner` class) still requires to perform string-based comparison.

I really like the idea (you suggested) of leveraging the extensibility of `struct` types! I am thinking about using it for `ComparatorType` - would be great to try that out.

For now I'd prefer to wait a bit before we land this PR and explore all possible alternatives and use cases we can think of.

**Comment by rustle** [comment]
> Thanks @rustle, the code looks good, but I am still a bit unsure if we need it, and if so, it's probably because we have some general design issue. Few thoughts:
> 
> * `tag` was supposed to be used only as a plain text prefix to distinguish output coming from different comparators.
> * `tag` is not supposed to be any kind of identifier, we want the `ComparatorType` to identify a comparator.

For these first two, when consuming this as a native library `ComparatorType` isn't that useful as an identifier as soon you have more than one custom `Comparator`.

> * Having a full list of comparators in `ComparatorType` and `ComparatorTag` might be a little bit confusing.
> * `ComparatorTag` does not change a lot from the internal implementation perspective i.e.  `ComparatorTag.dependencies` is used only once in the library code (second usage is in the tests where the string repetition IMHO is acceptable) so the benefit of having the string being statically predefined is not very clear.

This doesn't hold true if I want to make a custom `Comparator` and then identify it's results appropriately during rendering.

> * To select individual comparator or a subset, an array of `ComparatorType` needs to be specified, the use case of filtering by tag (as we do it in `CommandRunner` class) still requires to perform string-based comparison.

I'm not trying to avoid making comparisons, I'm trying to make comparisons reliable and simple given the constraints of the type system.

> I really like the idea (you suggested) of leveraging the extensibility of `struct` types! I am thinking about using it for `ComparatorType` - would be great to try that out.

Sure, that might work if you want to change `ComparatorType` instead of adding `ComparatorTag`

> For now I'd prefer to wait a bit before we land this PR and explore all possible alternatives and use cases we can think of.

**Comment by marciniwanicki** [comment]
I used mostly your implementation of the `ComparatorTag`, just removed all the static members. 

```swift
public struct ComparatorTag: RawRepresentable, ExpressibleByStringLiteral, Equatable, Encodable {
    // no static fields

    public var rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public init(stringLiteral value: String) {
        rawValue = value
    }
}
```

```swift
public struct ComparatorType {
    public static let fileReferences: ComparatorType = .init(FileReferencesComparator())
    public static let targets: ComparatorType = .init(TargetsComparator())
    public static let headers: ComparatorType = .init(HeadersComparator())
    public static let sources: ComparatorType = .init(SourcesComparator())
    public static let resources: ComparatorType = .init(ResourcesComparator())
    public static let configurations: ComparatorType = .init(ConfigurationsComparator())
    public static let settings: ComparatorType = .init(SettingsComparator())
    public static let resolvedSettings: ComparatorType = .init(ResolvedSettingsComparator(system: DefaultSystem()))
    public static let sourceTrees: ComparatorType = .init(SourceTreesComparator())
    public static let dependencies: ComparatorType = .init(DependenciesComparator())

    public let tag: ComparatorTag
    private let factory: () -> Comparator

    public init(_ factory: @escaping @autoclosure () -> Comparator) {
        self.factory = factory
        tag = factory().tag
    }

    private init(_ factory: @escaping () -> Comparator) {
        self.factory = factory
        tag = factory().tag
    }

    @available(*, deprecated, message: "Please use init instead")
    public static func custom(_ factory: @escaping @autoclosure () -> Comparator) -> ComparatorType {
        return ComparatorType(factory)
    }

    func comparator() -> Comparator {
        return factory()
    }
}
```

and the comparator would still specify its own tag string, i.e.

```swift
final class TargetsComparator: Comparator {
    let tag: ComparatorTag = "targets"
...
```

- We get the type safety but don't maintain two list of the comparators.

What's your thoughts @rustle ? Would it help?

**Comment by rustle** [comment]
I'm pretty convinced the right thing to do is to lose ComparatorType and ComparatorTag and just have a namespace struct (not one you actually construct. I called it Comparators in my last commit.

For reference here's a rough sketch of the code I'm trying to write. Eventually this would grow into a UI that can display each type, which is why I want to be able to sort results into bins.

https://gist.github.com/rustle/5bc1b1b916fb1d24164f1b2637df333e

I probably eventually want `ProjectComparatorResult` and `CompareResult` to change a fair bit to make the mapping from this comparator to these results less lossy.

My change doesn't address it completely but I'd also like to stop making comparators just to ask them for a constant.

**Comment by rustle** [comment]
Maybe the move is just going with your latest version @marciniwanicki but passing in the string identifier to the `ComparatorType` and having the built in `Comparator`s take an identifier in their init(). I could take or leave the simplified `ComparatorTag`

**Comment by marciniwanicki** [comment]
Thanks @rustle for your patience and all the suggestions. It took me a while to see it, but I agree the strongly typed tag is useful. I can see it being handy in a custom comparator case (while using a custom renderer or raw result).

Internally in the library I do not see much value in maintaining a list of `ComaratorTag`s, so I'd prefer to keep them as they are now - defined inside the comparators (at least for now, maybe we will move them one day when we have a valid use case). However, since the `ComparatorTag` is a struct, for all the custom comparators you can do exactly what you suggested: create an extension, define the custom tags and pass them via `init` or use directly in your comparators. 

i.e.
```swift
extension ComparatorTag {
    static let myCustomComparator1: ComparatorTag = "myCustomComparator1"
    static let myCustomComparator1: ComparatorTag = "myCustomComparator1"
}
```

```swift
class MyCustomComaprator: Comparator {
    let tag = .myCustomComparator1
}
```


I've pushed few small changes which make the `ComparatorType` a bit better than before. In most cases `init` with a `Comparator` instance should be used as the comparators SHOULD be stateless. However, if for some reason they're not, users can still pass a factory.
https://github.com/marciniwanicki/xcdiff/tree/spike/strongly-typed-comparator-tag

`CompareResult` will new get `ComparatorTag`:
```swift
public struct CompareResult: GenericCompareResult, Equatable {
    public struct DifferentValues: Encodable, Equatable {
        public let context: String
        public let first: String
        public let second: String

        public init(context: String,
                    first: String? = nil,
                    second: String? = nil) {
            self.context = context
            self.first = first ?? "nil"
            self.second = second ?? "nil"
        }
    }

    public let tag: ComparatorTag
    public let context: [String]
    public let description: String?
    public let onlyInFirst: [String]
    public let onlyInSecond: [String]
    public let differentValues: [DifferentValues]
```

**Comment by marciniwanicki** [comment]
Actually, both `Either` and 

```swift
 public init(_ factory: @escaping () -> Comparator) {
        comparatorOrFactory = .right(factory)
        tag = factory().tag
    }
```

could be removed, we don't need the laziness.. we can bring it back in the future if needed.

**Pull request closed without merging**
