### PR TITLE
Rendered result

### PR DESCRIPTION
**Pull request by rustle**
*Issue number of the reported bug or feature request: #<number>*

**Describe your changes**
Allow ResultRenderer to return a parameterized type

**Testing performed**
Existing tests sufficient

**Additional context**
Makes XCDiffCore more generally useful as a library for things other than a command line tool.

### CODE REVIEW

**Comment by marciniwanicki** [comment]
Hey @rustle again :) If I understand correctly, the ultimate goal is to allow users to define custom renderers that can produce different kind of output than `String`. Do you have any examples what different output types would your or the users like to output? 

As you pointed out 👍, `ProjectComparator` does not allow to pass custom renderer and control the output. We simplify the API and tailored it to our internal needs but I totally agree it could be done better. 

I was thinking about decoupling `ProjectComparator` and rendering code so those 2 could be used independently. `ProjectComparator` could return raw `ProjectCompareResult` which would allow to use the raw data without passing it through the rendering step or use renderer separately if needed.

**Comment by rustle** [comment]
@marciniwanicki emitting the result directly without a renderer would be nice. I think supporting custom renderers is a good start for now though.

**Comment by rustle** [comment]
Not sure why the build is failing. fatalError() to abstract methods with return values isn't a new feature. make clean build succeeds for me on Catalina with 11.2 (11B52)

**Comment by marciniwanicki** [comment]
- I think the build failed because we use Xcode 10.3 and Swift 5.0 compiler on the CI (check out `.travis.yml` in the root project directory). Omitting `return` is 5.1 feature (we will switch at some point).

```
public func compare(_ firstPath: Path,
                        _ secondPath: Path,
                        parameters: ComparatorParameters) throws -> Result<RenderedResult> {
        try upstream.compare(firstPath,
                             secondPath,
                             parameters: parameters)
    }
```
- On the other hand `fatalError` is something we generally want to avoid in the library code (in tests it's fine), as it's pretty much untestable :( 
- Would you mind to put a bit more context about other types of renderers? The only one that we were planning to add is HTML renderer but it's still String based. 
- The generic interface is great but on the other hand it complicates the usage and the implementation itself. We need a good use case to make sure the value compensates the costs 🙂

**Pull request closed without merging**
